# Generated by Django 5.2.8 on 2025-11-29 06:54

import colorfield.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_player_player_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='picked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=colorfield.fields.ColorField(default='#0000FF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
